name: task_flow
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Architecture & State Management
  stacked: ^3.4.3
  stacked_hooks: ^0.2.4
  stacked_services: ^1.5.0
  logger: ^1.4.0
  dartz: ^0.10.1
  async: ^2.11.0

  #Utils
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  # google_sign_in: ^6.2.1

  #UI
  flutter_screenutil: ^5.9.3
  table_calendar: ^3.1.2
  animations: ^2.0.11
  google_fonts: ^6.2.1
  adaptive_dialog: ^2.1.0
  sign_in_button: ^3.2.0
  flutter_snake_navigationbar: ^0.6.1
  omni_datetime_picker: ^2.0.3
  scroll_to_index: ^3.0.1
  # board_datetime_picker:
  #   git:
  #     url: https://github.com/KhalilAmor/board_datetime_picker
  #     ref: main

  #Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  cloud_functions: ^5.0.2
  firebase_storage: ^12.1.0

# dependency_overrides:
#   http: ^1.1.0

#Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  mockito: ^5.4.4
  stacked_generator: ^1.6.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
