name: task_flow
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Architecture & State Management
  stacked: ^3.4.2
  stacked_hooks: ^0.2.3
  stacked_services: ^1.3.0
  logger: ^1.4.0
  dartz: ^0.10.1
  async: ^2.11.0

  #Utils
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  # google_sign_in: ^6.2.1

  #UI
  flutter_screenutil: ^5.9.0
  animations:
  google_fonts: ^6.1.0
  # flutter_signin_button: ^2.0.0
  flutter_snake_navigationbar: ^0.6.1
  omni_datetime_picker: ^1.0.9
  # board_datetime_picker:
  #   git:
  #     url: https://github.com/KhalilAmor/board_datetime_picker
  #     ref: main

  #Firebase
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.15.3
  cloud_functions: ^4.6.4

# dependency_overrides:
#   http: ^1.1.0

#Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mockito: ^5.4.2
  stacked_generator: ^1.5.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
