import 'package:flutter/material.dart';

List<int> iconsList = [
  Icons.home.codePoint,
  Icons.work.codePoint,
  Icons.private_connectivity.codePoint,
  Icons.person.codePoint,
  Icons.school.codePoint,
  Icons.pets.codePoint,
  Icons.fitness_center.codePoint,
  Icons.palette.codePoint,
  Icons.music_note.codePoint,
  Icons.book.codePoint,
  Icons.local_cafe.codePoint,
  Icons.computer.codePoint,
  Icons.local_florist.codePoint,
  Icons.local_dining.codePoint,
  Icons.directions_bike.codePoint,
  Icons.camera_alt.codePoint,
  Icons.family_restroom.codePoint,
  Icons.airplanemode_active.codePoint,
  Icons.attach_money.codePoint,
  Icons.healing.codePoint,
  Icons.movie.codePoint,
  Icons.build.codePoint,
];
